import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import { centraFonts } from "@/utils/customFont";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Dream Lead Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${centraFonts.variable} font-centra text-primaryText scroll-smooth`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
